# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "walkupon"
client_id = "d1580b38d25d02989a27e29a93a611dd"
application_url = "https://checkout-deposits-dayton-cure.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://checkout-deposits-dayton-cure.trycloudflare.com/auth/callback",
  "https://checkout-deposits-dayton-cure.trycloudflare.com/auth/shopify/callback",
  "https://checkout-deposits-dayton-cure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "walkupon.myshopify.com"
